config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  authenticate :user do
    namespace :webapp, module: :webapp do
      resources :transactions
      resources :categories
    end

    namespace :console, module: :console do
      get "dashboard", to: "dashboard#index"
      resources :categories
      resources :transactions
      resources :subscriptions
    end
  end

  root "console/dashboard#index"
end

app/controllers/console/transactions_controller.rb
class Console::TransactionsController < ConsoleController
  include TransactionsConcern
  before_action :set_transaction, only: [ :edit, :update, :destroy ]
  before_action :set_categories, only: [ :edit, :new, :update, :index, :create ]

  def index
    policy_scope(Transaction)
    params[:q] ||= { date_gteq: Date.today.beginning_of_month, date_lteq: Date.today.end_of_month }

    if params[:apply_subscriptions].present?
      SubscriptionsService.new(current_user).apply
      flash[:success] = t("labels.subscriptions_applied")
    end
    @q = current_user.transactions.ransack(params[:q])
    @transactions = @q.result
    @transactions_report = TransactionReportService.new(@transactions, params[:q][:date_gteq].to_s, params[:q][:date_lteq].to_s).generate
    authorize(@transactions)
  end

  def new
    policy_scope(Transaction)
    @transaction_type = params[:transaction_type] if Transaction.transaction_types.keys.include?(params[:transaction_type])
    @transaction = current_user.transactions.build
    authorize @transaction
  end

  def create
    policy_scope(Transaction)
    @transaction = current_user.transactions.build(transaction_params)
    authorize @transaction
    if @transaction.save
      redirect_to console_transactions_path, notice: t("labels.record_created")
    else
      render :new
    end
  end

  def update
    authorize @transaction
    if @transaction.update(transaction_params)
      redirect_to console_transactions_path, notice: t("labels.record_modified")
    else
      render :edit
    end
  end

  def destroy
    policy_scope(@transaction)
    authorize @transaction
    if @transaction.destroy
      flash[:success] = t("labels.record_destroyed")
    else
      flash[:danger] = "<b>#{t('labels.error_record_destroyed')}</b>: #{@transaction.errors.full_messages.join(". ")}"
    end
    redirect_to console_transactions_path
  end
end

app/controllers/webapp/categories_controller.rb
class Webapp::CategoriesController < WebappController
  include CategoriesConcern
  before_action :set_category, only: [ :edit, :update ]

  def create
    policy_scope(Category)
    @category = current_user.categories.new(category_params)
    authorize @category

    if @category.save
      flash[:success] = t("labels.record_created")
      redirect_to webapp_categories_path, success: t("labels.record_created")
    else
      flash[:danger] = @category.errors.full_messages.join("<br>").html_safe
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize(@category)
    if @category.update(category_params)
      redirect_to webapp_categories_path, notice: t("labels.record_modified")
    else
      render :edit
    end
  end
end

app/controllers/webapp/transactions_controller.rb
class Webapp::TransactionsController < WebappController
  include TransactionsConcern
  before_action :set_transaction, only: [ :edit, :update ]
  before_action :set_categories, only: [ :edit, :new ]

  def index
    policy_scope(Transaction)
    @transactions = current_user.transactions.order(id: :desc)
    authorize(@transactions)
  end

  def new
    @transaction = policy_scope(Transaction).new
    @transaction_type = params[:transaction_type] if Transaction.transaction_types.keys.include?(params[:transaction_type])
    authorize @transaction
  end

  def create
    policy_scope(Transaction)
    @transaction = current_user.transactions.new(transaction_params)
    authorize @transaction
    if @transaction.save
      flash[:success] = t("labels.record_created")
      redirect_to new_webapp_transaction_path, success: t("labels.record_created")
    else
      flash[:danger] = @transaction.errors.full_messages.join("<br>").html_safe
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @transaction
    if @transaction.update(transaction_params)
      redirect_to webapp_transactions_path, notice: t("labels.record_modified")
    else
      render :edit
    end
  end
end

app/controllers/webapp_controller.rb
class WebappController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized
  after_action :verify_policy_scoped
  layout "webapp"
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/webapp/transactions/_form.html.erb
<%= form_for [:webapp, @transaction], class: '' do |f| %>
  <div class="row mb-0">
    <div class="form-group">

      <div class="mb-0">
        <%= f.label :description, class: 'form-label form-control-lg' %>
        <%= f.text_field :description,
                         class: 'form-control form-control-lg',
                         autofocus: true,
                         required: true,
                         enterkeyhint: 'next' %>
      </div>

      <div class="mb-0">
        <%= f.label :category_id, class: 'form-label form-control-lg' %>
        <%= f.select :category_id,
                     options_from_collection_for_select(@categories, :id, :name, selected: @transaction.category_id),
                     { include_blank: '---', required: true, default: 'q' },
                     class: 'form-control form-control-lg' %>
        <%= link_to 'Handle categories', webapp_categories_path, class: '' %>
      </div>

      <div class="mb-0">
        <%= f.label :date, class: 'form-label form-control-lg' %>
        <%= f.date_field :date,
                         class: 'form-control form-control-lg',
                         autocomplete: 'off',
                         data: { field: :title },
                         placeholder: 'e.g. coffee with colleagues',
                         required: true %>
      </div>

      <div class="text-end">
        <button type="button" data-controller="transactions" data-action="click->transactions#setDateField" data-transactions-day="yesterday" class="btn btn-secondary mt-2 text-end">Yesterday</button>
        <button type="button" data-controller="transactions" data-action="click->transactions#setDateField" data-transactions-day="today" class="btn btn-secondary mt-2 text-end">Today</button>
      </div>

      <div class="mb-3">
        <%= f.label :amount, class: 'form-label form-control-lg' %>
        <div class="input-group">
          <span class="input-group-text">€</span>
          <%= f.number_field :amount,
                             class: 'form-control form-control-lg',
                             step: '0.01',
                             required: true,
                             inputmode: 'decimal' %>
        </div>
      </div>

      <div class="mb-0 col-sm-offset-2 text-end">
        <%= f.hidden_field :transaction_type, value: @transaction_type || f.object.transaction_type %>
        <%= f.submit 'Save', class: 'btn btn-primary btn-lg' %>
      </div>
    </div>


  </div>
<% end %>

app/views/webapp/transactions/_transaction_card.html.erb
<div class="card mb-2">
  <div class="card-body">
    <div class="d-flex justify-content-between align-items-center mb-2">
      <span class="text-muted">
       <%= link_to edit_webapp_transaction_path(transaction), class: 'link-underline link-underline-opacity-0 text-black' do %>
        <%= transaction.date %>
       <%- end %>
      </span>
    </div>
    <%= link_to edit_webapp_transaction_path(transaction), class: 'mb1 link-underline link-underline-opacity-0 text-black h5' do %>
      <%= transaction.description %>
    <%- end %>
    <div class="d-flex justify-content-between">
      <span class="fw-bold">
        <%= link_to edit_webapp_transaction_path(transaction), class: 'link-underline link-underline-opacity-0 text-black' do %>
        € <%= transaction.amount %>
        <%- end %>
      </span>
      <%= link_to edit_webapp_category_path(transaction.category), class: '' do %>
      <span class="badge" style="background: <%= transaction.category.hex_color.present? ? transaction.category.hex_color : "gray" %>">
        <%= transaction.category.name %>
      </span>
      <%- end %>
    </div>
  </div>
</div>

app/views/webapp/transactions/edit.html.erb
<div class="container my-3">
  <p class="h2">  <%= link_to '<', webapp_transactions_path, class: 'btn btn-outline-secondary btn-lg' %>
    Edit <%= @transaction.transaction_type.capitalize %></p>
</div>
<div class="container my-3">
  <%= render 'form' %>
</div>

app/views/webapp/transactions/index.html.erb
<div class="container my-3">
  <div class="row">
    <div class="col text-start">
      <h1>Transactions</h1>
    </div>
    <div class="col text-end">
      <%= link_to t('activerecord.labels.transaction.new_income'), new_webapp_transaction_path(transaction_type: 'income'), class: 'btn btn-success -btn-lg' %>
      <%= link_to t('activerecord.labels.transaction.new_expense'), new_webapp_transaction_path(transaction_type: 'expense'), class: 'btn btn-danger -btn-lg' %>
    </div>
  </div>
</div>
<div class="container my-3">
  <%= link_to 'Go to categories', webapp_categories_path, class: 'link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover' %>
</div>
<div class="container my-3">
  <% if @transactions.any? %>
    <%= render partial: 'webapp/transactions/transaction_card', collection: @transactions, as: :transaction %>
  <% else %>
    <div class="alert alert-info" role="alert">
      <%= t('labels.no_transactions') %>
    </div>
  <% end %>
</div>

app/views/webapp/transactions/new.erb
<div class="container my-3">
  <p class="h2">  <%= link_to '<', webapp_transactions_path, class: 'btn btn-outline-secondary' %>
    New <%= @transaction_type.present? ? t("activerecord.labels.transaction.#{@transaction_type}") :
              t("activerecord.models.transaction.one") %></p>
</div>
<div class="container my-3">
  <%= render 'form' %>
</div>