config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  authenticate :user do
    namespace :webapp, module: :webapp do
      resources :transactions
      resources :categories
    end

    namespace :console, module: :console do
      get "dashboard", to: "dashboard#index"
      resources :categories
      resources :transactions
      resources :subscriptions
    end
  end

  root "console/dashboard#index"
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  enum :subscription_type, { monthly: 0, annual: 1, quarterly: 2, semiannual: 3 }
  belongs_to :user
  validates :description, :default_amount, :subscription_type, presence: true
  validates :code, uniqueness: true
  before_create :create_subscription_code

  private

  def create_subscription_code
    self.code = SecureRandom.hex(10)
  end
end

app/controllers/console/categories_controller.rb
class Console::CategoriesController < ConsoleController
  include CategoriesConcern
  before_action :set_category, only: [ :edit, :update, :destroy ]

  def create
    policy_scope(Category)
    @category = current_user.categories.build(category_params)
    authorize @category
    if @category.save
      redirect_to console_categories_path, notice: t("labels.record_created")
    else
      render :new
    end
  end

  def update
    authorize @category
    if @category.update(category_params)
      redirect_to console_categories_path, notice: t("labels.record_modified")
    else
      render :edit
    end
  end

  def destroy
    policy_scope(@category)
    authorize @category
    if @category.destroy
      flash[:success] = t("labels.record_destroyed")
      redirect_to console_categories_path
    else
      flash[:danger] = "<b>#{t('labels.error_record_destroyed')}</b>: #{@category.errors.full_messages.join(". ")}"
      redirect_to console_categories_path
    end
  end
end

app/controllers/console/dashboard_controller.rb
class Console::DashboardController < ConsoleController
  def index
    policy_scope(Transaction)
    @categories = current_user.categories
    params[:q] ||= {}
    authorize(Transaction)
    if params.dig(:q, :date_eq).present?
      year = params[:q][:date_eq]
      params[:q][:date_gteq] = "#{year}-01-01"
      params[:q][:date_lteq] = "#{year}-12-31"
    end

    @q = current_user.transactions.ransack(params[:q])
    @transactions = @q.result
    transactions_data = @transactions.group(:category_id, Arel.sql("MONTH(date)")).sum(:amount)

    @category_data = build_category_data(@categories, transactions_data)
  end

  protected

  def build_category_data(categories, transactions_data)
    category_data = {}
    categories.each do |category|
      monthly_sums = (1..12).map { |m| transactions_data[[ category.id, m ]] || 0 }
      total = monthly_sums.sum
      avg = total / 12.0

      category_data[category.id] = {
        name: category.name,
        color: category.hex_color,
        monthly_sums: monthly_sums,
        total: total,
        avg: avg
      }
    end
    category_data
  end
end

app/controllers/console/subscriptions_controller.rb
class Console::SubscriptionsController < ConsoleController
  before_action :set_subscription, only: [ :edit, :update, :destroy ]
  def index
    policy_scope(Subscription)
    @subscriptions = current_user.subscriptions
    authorize(@subscriptions)
  end

  def new
    policy_scope(Subscription)
    @subscription = current_user.subscriptions.build
    authorize @subscription
  end

  def edit
    authorize @subscription
  end

  def create
    policy_scope(Subscription)
    @subscription = current_user.subscriptions.build(subscription_params)
    authorize @subscription
    if @subscription.save
      redirect_to console_subscriptions_path, notice: t("labels.record_created")
    else
      render :new
    end
  end

  def update
    authorize @subscription
    if @subscription.update(subscription_params)
      redirect_to console_subscriptions_path, notice: t("labels.record_modified")
    else
      render :edit
    end
  end

  def destroy
    policy_scope(@subscription)
    authorize @subscription
    if @subscription.destroy
      flash[:success] = t("labels.record_destroyed")
      redirect_to console_subscriptions_path
    else
      flash[:danger] = "<b>#{t('labels.error_record_destroyed')}</b>: #{@subscription.errors.full_messages.join(". ")}"
      redirect_to console_subscriptions_path
    end
  end

  private

  def subscription_params
    params.require(:subscription).permit(:description, :default_amount, :subscription_type)
  end

  def set_subscription
    policy_scope(Subscription)
    @subscription = current_user.subscriptions.find(params[:id])
  end
end

app/controllers/console/transactions_controller.rb
class Console::TransactionsController < ConsoleController
  include TransactionsConcern
  before_action :set_transaction, only: [ :edit, :update, :destroy ]
  before_action :set_categories, only: [ :edit, :new, :update, :index, :create ]

  def index
    policy_scope(Transaction)
    params[:q] ||= { date_gteq: Date.today.beginning_of_month, date_lteq: Date.today.end_of_month }

    if params[:apply_subscriptions].present?
      SubscriptionsService.new(current_user).apply
      flash[:success] = t("labels.subscriptions_applied")
    end
    @q = current_user.transactions.ransack(params[:q])
    @transactions = @q.result
    @transactions_report = TransactionReportService.new(@transactions, params[:q][:date_gteq].to_s, params[:q][:date_lteq].to_s).generate
    authorize(@transactions)
  end

  def new
    policy_scope(Transaction)
    @transaction_type = params[:transaction_type] if Transaction.transaction_types.keys.include?(params[:transaction_type])
    @transaction = current_user.transactions.build
    authorize @transaction
  end

  def create
    policy_scope(Transaction)
    @transaction = current_user.transactions.build(transaction_params)
    authorize @transaction
    if @transaction.save
      redirect_to console_transactions_path, notice: t("labels.record_created")
    else
      render :new
    end
  end

  def update
    authorize @transaction
    if @transaction.update(transaction_params)
      redirect_to console_transactions_path, notice: t("labels.record_modified")
    else
      render :edit
    end
  end

  def destroy
    policy_scope(@transaction)
    authorize @transaction
    if @transaction.destroy
      flash[:success] = t("labels.record_destroyed")
    else
      flash[:danger] = "<b>#{t('labels.error_record_destroyed')}</b>: #{@transaction.errors.full_messages.join(". ")}"
    end
    redirect_to console_transactions_path
  end
end

app/controllers/console_controller.rb
class ConsoleController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized
  after_action :verify_policy_scoped
  layout "console"
end

app/views/console/subscriptions/_form.html.erb
<%= form_for [:console, @subscription], class: 'mb-4' do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@subscription.errors.count, "error") %>:</h2>
      <ul>
        <% @subscription.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :description, t('activerecord.attributes.subscription.description'), class: "form-label" %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :default_amount, class: 'form-label' %>
    <div class="input-group">
      <span class="input-group-text">€</span>
      <%= f.number_field :default_amount,
                         class: 'form-control form-control',
                         step: '0.01',
                         required: true,
                         inputmode: 'decimal' %>
    </div>
  </div>

  <div class="mb-3">
    <%= f.label :subscription_type, t('activerecord.attributes.subscription.subscription_type'), class: 'form-label' %>
    <div>
      <%= f.radio_button :subscription_type, 'monthly', class: 'form-check-input', required: true %>
      <%= f.label :subscription_type_monthly, t('labels.monthly'), class: 'form-check-label' %>
    </div>
    <div>
      <%= f.radio_button :subscription_type, 'annual', class: 'form-check-input', required: true %>
      <%= f.label :subscription_type_annual, t('labels.annual'), class: 'form-check-label' %>
    </div>
    <div>
      <%= f.radio_button :subscription_type, 'quarterly', class: 'form-check-input', required: true %>
      <%= f.label :subscription_type_quarterly, t('labels.quarterly'), class: 'form-check-label' %>
    </div>
    <div>
      <%= f.radio_button :subscription_type, 'semiannual', class: 'form-check-input', required: true %>
      <%= f.label :subscription_type_semiannual, t('labels.semiannual'), class: 'form-check-label' %>
    </div>
  </div>

  <div class="mb-3">
    <%= f.submit @subscription.new_record? ? t('labels.new') : t('labels.update'), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/console/subscriptions/_subscription.html.erb
<tr>
  <td><%= subscription.description %></td>
  <td><%= currency_formatter(subscription.default_amount) %></td>
  <td><%= subscription.subscription_type %></td>
  <td>
    <div class="d-inline-block">
      <%= link_to t('labels.edit'), edit_console_subscription_path(subscription), class: "btn btn-sm btn-link d-inline" %>
    </div>
    <div class="d-inline-block">
      <%= button_to t('labels.destroy'), console_subscription_path(subscription), method: :delete, class: "btn btn-sm btn-link d-inline" %>
    </div>
  </td>
</tr>

app/views/console/subscriptions/edit.html.erb
<h2>Edit Subscription</h2>

<%= render 'form', subscription: @subscription %>

<%= link_to t('labels.back'), console_subscriptions_path %>

app/views/console/subscriptions/index.html.erb
<h2>Subscriptions</h2>
<div class="text-end">
  <%= link_to t('labels.new'), new_console_subscription_path, class: 'btn btn-sm btn-primary' %>
</div>

<div class="table-responsive small">
  <table class="table table-sm">
    <thead>
    <tr>
      <th scope="col"><%= t('activerecord.attributes.subscription.description') %></th>
      <th scope="col"><%= t('activerecord.attributes.subscription.default_amount') %></th>
      <th scope="col"><%= t('activerecord.attributes.subscription.subscription_type') %></th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'console/subscriptions/subscription', collection: @subscriptions, as: :subscription %>
    </tbody>
  </table>
</div>

app/views/console/subscriptions/new.html.erb
<h2>New Category</h2>

<%= render 'form', subscription: @subscription %>

<%= link_to t('labels.back'), console_subscriptions_path %>