config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  authenticate :user do
    namespace :webapp, module: :webapp do
      resources :transactions
      resources :categories
    end

    namespace :console, module: :console do
      get "dashboard", to: "dashboard#index"
      resources :categories
      resources :transactions
      resources :subscriptions
    end
  end

  root "console/dashboard#index"
end

app/models/category.rb
class Category < ApplicationRecord
  enum :category_type, { expenses: 0, incomes: 1, subscriptions: 2 }
  belongs_to :user
  has_many :transactions
  validates :name, :hex_color, presence: true
  validates :name, uniqueness: { scope: :user_id }
  validates :hex_color, format: { with: /\A#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})\z/ }
  validates :category_type, presence: true

  scope :expenses, -> { where(category_type: :expenses) }
  scope :incomes, -> { where(category_type: :incomes) }

  class << self
    alias :expense :expenses
    alias :income :incomes
  end

  before_destroy :check_for_transactions


  def self.ransackable_attributes(auth_object = nil)
    %w[created_at hex_color id name updated_at user_id]
  end

  private

  def check_for_transactions
    if transactions.exists?
      errors.add(:base, "Cannot delete category with associated transactions")
      throw(:abort)
    end
  end
end

app/controllers/console/categories_controller.rb
class Console::CategoriesController < ConsoleController
  include CategoriesConcern
  before_action :set_category, only: [ :edit, :update, :destroy ]

  def create
    policy_scope(Category)
    @category = current_user.categories.build(category_params)
    authorize @category
    if @category.save
      redirect_to console_categories_path, notice: t("labels.record_created")
    else
      render :new
    end
  end

  def update
    authorize @category
    if @category.update(category_params)
      redirect_to console_categories_path, notice: t("labels.record_modified")
    else
      render :edit
    end
  end

  def destroy
    policy_scope(@category)
    authorize @category
    if @category.destroy
      flash[:success] = t("labels.record_destroyed")
      redirect_to console_categories_path
    else
      flash[:danger] = "<b>#{t('labels.error_record_destroyed')}</b>: #{@category.errors.full_messages.join(". ")}"
      redirect_to console_categories_path
    end
  end
end

app/controllers/console/dashboard_controller.rb
class Console::DashboardController < ConsoleController
  def index
    policy_scope(Transaction)
    @categories = current_user.categories
    params[:q] ||= {}
    authorize(Transaction)
    if params.dig(:q, :date_eq).present?
      year = params[:q][:date_eq]
      params[:q][:date_gteq] = "#{year}-01-01"
      params[:q][:date_lteq] = "#{year}-12-31"
    end

    @q = current_user.transactions.ransack(params[:q])
    @transactions = @q.result
    transactions_data = @transactions.group(:category_id, Arel.sql("MONTH(date)")).sum(:amount)

    @category_data = build_category_data(@categories, transactions_data)
  end

  protected

  def build_category_data(categories, transactions_data)
    category_data = {}
    categories.each do |category|
      monthly_sums = (1..12).map { |m| transactions_data[[ category.id, m ]] || 0 }
      total = monthly_sums.sum
      avg = total / 12.0

      category_data[category.id] = {
        name: category.name,
        color: category.hex_color,
        monthly_sums: monthly_sums,
        total: total,
        avg: avg
      }
    end
    category_data
  end
end

app/controllers/console/subscriptions_controller.rb
class Console::SubscriptionsController < ConsoleController
  before_action :set_subscription, only: [ :edit, :update, :destroy ]
  def index
    policy_scope(Subscription)
    @subscriptions = current_user.subscriptions
    authorize(@subscriptions)
  end

  def new
    policy_scope(Subscription)
    @subscription = current_user.subscriptions.build
    authorize @subscription
  end

  def edit
    authorize @subscription
  end

  def create
    policy_scope(Subscription)
    @subscription = current_user.subscriptions.build(subscription_params)
    authorize @subscription
    if @subscription.save
      redirect_to console_subscriptions_path, notice: t("labels.record_created")
    else
      render :new
    end
  end

  def update
    authorize @subscription
    if @subscription.update(subscription_params)
      redirect_to console_subscriptions_path, notice: t("labels.record_modified")
    else
      render :edit
    end
  end

  def destroy
    policy_scope(@subscription)
    authorize @subscription
    if @subscription.destroy
      flash[:success] = t("labels.record_destroyed")
      redirect_to console_subscriptions_path
    else
      flash[:danger] = "<b>#{t('labels.error_record_destroyed')}</b>: #{@subscription.errors.full_messages.join(". ")}"
      redirect_to console_subscriptions_path
    end
  end

  private

  def subscription_params
    params.require(:subscription).permit(:description, :default_amount, :subscription_type)
  end

  def set_subscription
    policy_scope(Subscription)
    @subscription = current_user.subscriptions.find(params[:id])
  end
end

app/controllers/console/transactions_controller.rb
class Console::TransactionsController < ConsoleController
  include TransactionsConcern
  before_action :set_transaction, only: [ :edit, :update, :destroy ]
  before_action :set_categories, only: [ :edit, :new, :update, :index, :create ]

  def index
    policy_scope(Transaction)
    params[:q] ||= { date_gteq: Date.today.beginning_of_month, date_lteq: Date.today.end_of_month }

    if params[:apply_subscriptions].present?
      SubscriptionsService.new(current_user).apply
      flash[:success] = t("labels.subscriptions_applied")
    end
    @q = current_user.transactions.ransack(params[:q])
    @transactions = @q.result
    @transactions_report = TransactionReportService.new(@transactions, params[:q][:date_gteq].to_s, params[:q][:date_lteq].to_s).generate
    authorize(@transactions)
  end

  def new
    policy_scope(Transaction)
    @transaction_type = params[:transaction_type] if Transaction.transaction_types.keys.include?(params[:transaction_type])
    @transaction = current_user.transactions.build
    authorize @transaction
  end

  def create
    policy_scope(Transaction)
    @transaction = current_user.transactions.build(transaction_params)
    authorize @transaction
    if @transaction.save
      redirect_to console_transactions_path, notice: t("labels.record_created")
    else
      render :new
    end
  end

  def update
    authorize @transaction
    if @transaction.update(transaction_params)
      redirect_to console_transactions_path, notice: t("labels.record_modified")
    else
      render :edit
    end
  end

  def destroy
    policy_scope(@transaction)
    authorize @transaction
    if @transaction.destroy
      flash[:success] = t("labels.record_destroyed")
    else
      flash[:danger] = "<b>#{t('labels.error_record_destroyed')}</b>: #{@transaction.errors.full_messages.join(". ")}"
    end
    redirect_to console_transactions_path
  end
end

app/controllers/console_controller.rb
class ConsoleController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized
  after_action :verify_policy_scoped
  layout "console"
end

app/controllers/webapp/categories_controller.rb
class Webapp::CategoriesController < WebappController
  include CategoriesConcern
  before_action :set_category, only: [ :edit, :update ]

  def create
    policy_scope(Category)
    @category = current_user.categories.new(category_params)
    authorize @category

    if @category.save
      flash[:success] = t("labels.record_created")
      redirect_to webapp_categories_path, success: t("labels.record_created")
    else
      flash[:danger] = @category.errors.full_messages.join("<br>").html_safe
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize(@category)
    if @category.update(category_params)
      redirect_to webapp_categories_path, notice: t("labels.record_modified")
    else
      render :edit
    end
  end
end

app/views/console/categories/_category.html.erb
<tr>
  <td style="background: <%= category.hex_color %>; width: 20px"></td>
  <td><%= category.name %></td>
  <td><%= category.category_type %></td>
  <td>
    <% if policy(category).edit? %>
      <div class="d-inline-block">
        <%= link_to t('labels.edit'), edit_console_category_path(category), class: "btn btn-sm btn-link d-inline" %>
      </div>
    <% end %>
    <div class="d-inline-block">
      <%= button_to t('labels.destroy'), console_category_path(category), method: :delete, class: "btn btn-sm btn-link d-inline" %>
    </div>
  </td>
</tr>

app/views/console/categories/_form.html.erb
<%= form_for [:console, @category], class: 'mb-4' do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@category.errors.count, "error") %>:</h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :name, "Nome", class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :hex_color, "Colore (HEX)", class: "form-label" %>
    <%= f.color_field :hex_color,
                      class: "form-control form-control-color",
                      style: "width: 3rem; padding: 0;",
                      value: f.object.hex_color || Faker::Color.hex_color %>
  </div>

  <div class="mb-3">
    <%= f.label :category_type, t('activerecord.attributes.category.category_type'), class: 'form-label' %>
    <div>
      <%= f.radio_button :category_type, 'expenses', class: 'form-check-input', required: true %>
      <%= f.label :category_type_expense, t('labels.expenses'), class: 'form-check-label' %>
    </div>
    <div>
      <%= f.radio_button :category_type, 'incomes', class: 'form-check-input', required: true %>
      <%= f.label :category_type_income, t('labels.incomes'), class: 'form-check-label' %>
    </div>
  </div>

  <div class="mb-3">
    <%= f.submit @category.new_record? ? t('labels.new') : t('labels.update'), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/console/categories/edit.html.erb
<h2>Edit Category</h2>

<%= render 'form', category: @category %>

<%= link_to t('labels.back'), console_categories_path %>

app/views/console/categories/index.html.erb
<h2>Categories</h2>
<div class="text-end">
  <%= link_to t('labels.new'), new_console_category_path, class: 'btn btn-sm btn-primary' %>
</div>

<div class="table-responsive small">
  <table class="table table-sm">
    <thead>
    <tr>
      <th scope="col"><%= t('activerecord.attributes.category.hex_color') %></th>
      <th scope="col"><%= t('activerecord.attributes.category.name') %></th>
      <th scope="col"><%= t('activerecord.attributes.category.category_type') %></th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'console/categories/category', collection: @categories, as: :category %>
    </tbody>
  </table>
</div>

app/views/console/categories/new.html.erb
<h2>New Subscription</h2>

<%= render 'form', category: @category %>

<%= link_to t('labels.back'), console_categories_path %>