config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  authenticate :user do
    namespace :webapp, module: :webapp do
      resources :transactions
      resources :categories
    end

    namespace :console, module: :console do
      get "dashboard", to: "dashboard#index"
      resources :categories
      resources :transactions
      resources :subscriptions
    end
  end

  root "console/dashboard#index"
end

app/controllers/console/categories_controller.rb
class Console::CategoriesController < ConsoleController
  include CategoriesConcern
  before_action :set_category, only: [ :edit, :update, :destroy ]

  def create
    policy_scope(Category)
    @category = current_user.categories.build(category_params)
    authorize @category
    if @category.save
      redirect_to console_categories_path, notice: t("labels.record_created")
    else
      render :new
    end
  end

  def update
    authorize @category
    if @category.update(category_params)
      redirect_to console_categories_path, notice: t("labels.record_modified")
    else
      render :edit
    end
  end

  def destroy
    policy_scope(@category)
    authorize @category
    if @category.destroy
      flash[:success] = t("labels.record_destroyed")
      redirect_to console_categories_path
    else
      flash[:danger] = "<b>#{t('labels.error_record_destroyed')}</b>: #{@category.errors.full_messages.join(". ")}"
      redirect_to console_categories_path
    end
  end
end

app/controllers/console/dashboard_controller.rb
class Console::DashboardController < ConsoleController
  def index
    policy_scope(Transaction)
    @categories = current_user.categories
    params[:q] ||= {}
    authorize(Transaction)
    if params.dig(:q, :date_eq).present?
      year = params[:q][:date_eq]
      params[:q][:date_gteq] = "#{year}-01-01"
      params[:q][:date_lteq] = "#{year}-12-31"
    end

    @q = current_user.transactions.ransack(params[:q])
    @transactions = @q.result
    transactions_data = @transactions.group(:category_id, Arel.sql("MONTH(date)")).sum(:amount)

    @category_data = build_category_data(@categories, transactions_data)
  end

  protected

  def build_category_data(categories, transactions_data)
    category_data = {}
    categories.each do |category|
      monthly_sums = (1..12).map { |m| transactions_data[[ category.id, m ]] || 0 }
      total = monthly_sums.sum
      avg = total / 12.0

      category_data[category.id] = {
        name: category.name,
        color: category.hex_color,
        monthly_sums: monthly_sums,
        total: total,
        avg: avg
      }
    end
    category_data
  end
end

app/controllers/console/subscriptions_controller.rb
class Console::SubscriptionsController < ConsoleController
  before_action :set_subscription, only: [ :edit, :update, :destroy ]
  def index
    policy_scope(Subscription)
    @subscriptions = current_user.subscriptions
    authorize(@subscriptions)
  end

  def new
    policy_scope(Subscription)
    @subscription = current_user.subscriptions.build
    authorize @subscription
  end

  def edit
    authorize @subscription
  end

  def create
    policy_scope(Subscription)
    @subscription = current_user.subscriptions.build(subscription_params)
    authorize @subscription
    if @subscription.save
      redirect_to console_subscriptions_path, notice: t("labels.record_created")
    else
      render :new
    end
  end

  def update
    authorize @subscription
    if @subscription.update(subscription_params)
      redirect_to console_subscriptions_path, notice: t("labels.record_modified")
    else
      render :edit
    end
  end

  def destroy
    policy_scope(@subscription)
    authorize @subscription
    if @subscription.destroy
      flash[:success] = t("labels.record_destroyed")
      redirect_to console_subscriptions_path
    else
      flash[:danger] = "<b>#{t('labels.error_record_destroyed')}</b>: #{@subscription.errors.full_messages.join(". ")}"
      redirect_to console_subscriptions_path
    end
  end

  private

  def subscription_params
    params.require(:subscription).permit(:description, :default_amount, :subscription_type)
  end

  def set_subscription
    policy_scope(Subscription)
    @subscription = current_user.subscriptions.find(params[:id])
  end
end

app/controllers/console/transactions_controller.rb
class Console::TransactionsController < ConsoleController
  include TransactionsConcern
  before_action :set_transaction, only: [ :edit, :update, :destroy ]
  before_action :set_categories, only: [ :edit, :new, :update, :index, :create ]

  def index
    policy_scope(Transaction)
    params[:q] ||= { date_gteq: Date.today.beginning_of_month, date_lteq: Date.today.end_of_month }

    if params[:apply_subscriptions].present?
      SubscriptionsService.new(current_user).apply
      flash[:success] = t("labels.subscriptions_applied")
    end
    @q = current_user.transactions.ransack(params[:q])
    @transactions = @q.result
    @transactions_report = TransactionReportService.new(@transactions, params[:q][:date_gteq].to_s, params[:q][:date_lteq].to_s).generate
    authorize(@transactions)
  end

  def new
    policy_scope(Transaction)
    @transaction_type = params[:transaction_type] if Transaction.transaction_types.keys.include?(params[:transaction_type])
    @transaction = current_user.transactions.build
    authorize @transaction
  end

  def create
    policy_scope(Transaction)
    @transaction = current_user.transactions.build(transaction_params)
    authorize @transaction
    if @transaction.save
      redirect_to console_transactions_path, notice: t("labels.record_created")
    else
      render :new
    end
  end

  def update
    authorize @transaction
    if @transaction.update(transaction_params)
      redirect_to console_transactions_path, notice: t("labels.record_modified")
    else
      render :edit
    end
  end

  def destroy
    policy_scope(@transaction)
    authorize @transaction
    if @transaction.destroy
      flash[:success] = t("labels.record_destroyed")
    else
      flash[:danger] = "<b>#{t('labels.error_record_destroyed')}</b>: #{@transaction.errors.full_messages.join(". ")}"
    end
    redirect_to console_transactions_path
  end
end

app/controllers/console_controller.rb
class ConsoleController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized
  after_action :verify_policy_scoped
  layout "console"
end

app/controllers/webapp/transactions_controller.rb
class Webapp::TransactionsController < WebappController
  include TransactionsConcern
  before_action :set_transaction, only: [ :edit, :update ]
  before_action :set_categories, only: [ :edit, :new ]

  def index
    policy_scope(Transaction)
    @transactions = current_user.transactions.order(id: :desc)
    authorize(@transactions)
  end

  def new
    @transaction = policy_scope(Transaction).new
    @transaction_type = params[:transaction_type] if Transaction.transaction_types.keys.include?(params[:transaction_type])
    authorize @transaction
  end

  def create
    policy_scope(Transaction)
    @transaction = current_user.transactions.new(transaction_params)
    authorize @transaction
    if @transaction.save
      flash[:success] = t("labels.record_created")
      redirect_to new_webapp_transaction_path, success: t("labels.record_created")
    else
      flash[:danger] = @transaction.errors.full_messages.join("<br>").html_safe
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @transaction
    if @transaction.update(transaction_params)
      redirect_to webapp_transactions_path, notice: t("labels.record_modified")
    else
      render :edit
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/console/transactions/_filters.html.erb
<h5>Search</h5>
<%= search_form_for @q, url: console_transactions_path, html: { role: 'search', id: 'search-box', class: 'filter-active' } do |f| %>
  <div class="row">
    <div class="col-sm-3 form-group has-feedback">
      <%= f.label :description_cont, Transaction.human_attribute_name(:description), class: 'control-label' %>
      <%= f.search_field :description_cont, class: 'form-control', placeholder: 'Find by description' %>
    </div>
    <div class="col-sm-3 form-group has-feedback">
      <%= f.label :category_name_cont, Category.human_attribute_name(:name), class: 'control-label' %>
      <%= f.search_field :category_name_cont, class: 'form-control', placeholder: 'Find by description' %>
    </div>
    <div class="col-sm-3 form-group has-feedback">
      <%= f.label :date_gteq, 'Start Date', class: 'control-label' %>
      <%= f.date_field :date_gteq, class: 'form-control', placeholder: 'Start Date' %>
    </div>
    <div class="col-sm-3 form-group has-feedback">
      <%= f.label :date_lteq, 'End Date', class: 'control-label' %>
      <%= f.date_field :date_lteq, class: 'form-control', placeholder: 'End Date' %>
      <div class="text-end">
        <button type="button" data-controller="transactions" data-action="click->transactions#setMonthField" data-transactions-month="all" class="btn btn-sm btn-secondary mt-2 text-end">All</button>
        <button type="button" data-controller="transactions" data-action="click->transactions#setMonthField" data-transactions-month="last-month" class="btn btn-sm btn-secondary mt-2 text-end">Last month</button>
        <button type="button" data-controller="transactions" data-action="click->transactions#setMonthField" data-transactions-month="this-month" class="btn btn-sm btn-secondary mt-2 text-end">This month</button>
      </div>
    </div>
  </div>
  <br>
  <%= f.submit 'Search', class: 'btn btn-outline-primary' %>
  <%= link_to 'Cancel', request.path, class: 'btn btn-white' %>
<% end %>
<hr>

app/views/console/transactions/_form.html.erb
<%= form_for [:console, @transaction], class: 'mb-4' do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@transaction.errors.count, "error") %>:</h2>
      <ul>
        <% @transaction.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :description, t('activerecord.attributes.transaction.description'), class: "form-label" %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :category_id, t('activerecord.attributes.transaction.category_id'), class: 'form-label' %>
    <%= f.select :category_id,
                 options_from_collection_for_select(@categories, :id, :name, selected: @transaction.category_id),
                 { include_blank: '---', required: true, default: 'q' },
                 class: 'form-control' %>

    <%= link_to 'Handle categories', console_categories_path, class: '' %>
  </div>


  <div class="mb-3">
    <%= f.label :date, t('activerecord.attributes.transaction.date'), class: 'form-label' %>
    <%= f.date_field :date,
                     class: 'form-control form-control',
                     autocomplete: 'off',
                     data: { field: :title },
                     placeholder: 'e.g. coffee with colleagues',
                     required: true %>
  </div>

  <div class="text-end">
    <button type="button" data-controller="transactions" data-action="click->transactions#setDateField" data-transactions-day="yesterday" class="btn btn-sm btn-secondary mt-2 text-end">Yesterday</button>
    <button type="button" data-controller="transactions" data-action="click->transactions#setDateField" data-transactions-day="today" class="btn btn-sm btn-secondary mt-2 text-end">Today</button>
  </div>

  <div class="mb-3">
    <%= f.label :amount, class: 'form-label' %>
    <div class="input-group">
      <span class="input-group-text">€</span>
      <%= f.number_field :amount,
                         class: 'form-control form-control',
                         step: '0.01',
                         required: true,
                         inputmode: 'decimal' %>
    </div>
  </div>

  <div class="mb-3">
    <%= f.label :paid, t('activerecord.attributes.transaction.paid'), class: 'form-label' %>
    <%= f.check_box :paid,
                    class: 'form-check-input',
                    required: true %>
  </div>
  <div class="mb-3">
    <%= f.label :transaction_type, t('activerecord.attributes.transaction.transaction_type'), class: 'form-label' %>
    <div>
      <%= f.radio_button :transaction_type, 'expense', class: 'form-check-input', required: true, checked: params[:transaction_type] == "expense" || f.object.transaction_type == "expense"  %>
      <%= f.label :transaction_type_expense, t('activerecord.labels.transaction.expense'), class: 'form-check-label' %>
    </div>
    <div>
      <%= f.radio_button :transaction_type, 'income', class: 'form-check-input', required: true, checked: params[:transaction_type] == "income" || f.object.transaction_type == "income" %>
      <%= f.label :transaction_type_income, t('activerecord.labels.transaction.income'), class: 'form-check-label' %>
    </div>
  </div>
  <div class="mb-3">
    <%= f.submit @transaction.new_record? ? t('labels.save') : t('labels.update'), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/console/transactions/_report.html.erb
<h5>Report</h5>
<div class="row">
  <div class="col-sm-12 form-group has-feedback">
    <table class="table table-bordered border-black">
      <tbody>
      <tr>
        <td>Total expenses:</td>
        <td><%= currency_formatter(@transactions_report[:total_expenses])%></td>
        <td>Total incomes:</td>
        <td><%= currency_formatter(@transactions_report[:total_incomes])%></td>
        <td>Saved:</td>
        <td><%= currency_formatter(@transactions_report[:saved]) %></td>
      </tr>
      <tr>
        <td>Expenses average as of today:</td>
        <td><%= currency_formatter(@transactions_report[:expenses_average_as_of_today]) %></td>
        <td>Expenses without subscriptions average as of today:</td>
        <td><%= currency_formatter(@transactions_report[:expenses_without_subscriptions_average_as_of_today]) %></td>
        <td>Expenses forecast:</td>
        <td><%= currency_formatter(@transactions_report[:expenses_forecast]) %></td>
      </tr>
      <tr>
        <td>Total days:</td>
        <td><%= @transactions_report[:total_days].to_i %></td>
        <td>Passed days:</td>
        <td><%= @transactions_report[:passed_days].to_i %></td>
        <td>Saving forecast:</td>
        <td><%= currency_formatter(@transactions_report[:expenses_forecast]) %></td>
      </tr>
      </tbody>
    </table>
  </div>
  <div class="col-sm-6 form-group has-feedback">
  </div>
</div>
<hr>

app/views/console/transactions/_transaction.html.erb
<tr>
  <td><%= transaction.date %></td>
  <td><%= transaction.description %></td>
  <td><span style="color: <%= transaction.category.hex_color %>">&#9632;</span> <%= transaction.category.name %></td>
  <td><%= currency_formatter(transaction.amount) %></td>
  <td><%= transaction.paid %></td>
  <td>
    <div class="d-inline-block">
      <%= link_to t('labels.edit'), edit_console_transaction_path(transaction), class: "btn btn-sm btn-link d-inline" %>
    </div>
    <div class="d-inline-block">
      <%= button_to t('labels.destroy'), console_transaction_path(transaction), method: :delete, class: "btn btn-sm btn-link d-inline" %>
    </div>
  </td>
</tr>

app/views/console/transactions/edit.html.erb
<h2>Edit <%= @transaction.transaction_type.capitalize %></h2>

<%= render 'form', transaction: @transaction %>

<%= link_to link_to t('labels.back'), console_transactions_path %>

app/views/console/transactions/index.html.erb
<h2>Transactions</h2>
<div class="text-end">
  <%= link_to t('activerecord.labels.transaction.apply_subscriptions'), console_transactions_path(apply_subscriptions: true), class: 'btn btn-sm btn-secondary' %>
  <%= link_to t('activerecord.labels.transaction.new_income'), new_console_transaction_path(transaction_type: 'income'), class: 'btn btn-sm btn-success' %>
    <%= link_to t('activerecord.labels.transaction.new_expense'), new_console_transaction_path(transaction_type: 'expense'), class: 'btn btn-sm btn-danger' %>
</div>

<%= render 'console/transactions/filters' %>
<%= render 'console/transactions/report' %>
<div class="table-responsive small">
  <table class="table table-sm">
    <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Description</th>
      <th scope="col">Category</th>
      <th scope="col">Amount</th>
      <th scope="col">Paid</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'console/transactions/transaction', collection: @transactions, as: :transaction %>
    </tbody>
  </table>
</div>

app/views/console/transactions/new.html.erb
<h2>New <%= @transaction_type.present? ? t("activerecord.labels.transaction.#{@transaction_type}") :
              t("activerecord.models.transaction.one") %></h2>

<%= render 'form', category: @transaction %>

<%= link_to t('labels.back'), console_transactions_path %>